from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
import os
from datetime import datetime

def create_matchmaking_pdf(filename, boy_details, girl_details, ashtakoota_score, result_message):
    doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title = Paragraph(f"<b><font size=16>Ashtakoota Match-Making Report</font></b><br/><font size=10>Generated by My Hindu API V4</font>", styles['Normal'])
    story.append(title)
    story.append(Spacer(1, 0.3*inch))
    
    # Couple Details
    story.append(Paragraph("<b>Birth Details</b>", styles['Heading2']))
    details = [
        ["Details", "Boy", "Girl"],
        ["Name", boy_details.get("name", "Boy"), girl_details.get("name", "Girl")],
        ["Birth Date", boy_details.get("dob"), girl_details.get("dob")],
        ["Birth Time", boy_details.get("time"), girl_details.get("time")],
        ["Birth Place", f"{boy_details.get('lat')}, {boy_details.get('lon')}", f"{girl_details.get('lat')}, {girl_details.get('lon')}"]
    ]
    t = Table(details, colWidths=[1.5*inch, 2.5*inch, 2.5*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))
    
    # Ashtakoota Milan Table
    story.append(Paragraph("<b>Guna Milan (Ashtakoota)</b>", styles['Heading2']))
    
    guna_data = [
        ["Koota", "Description", "Max Points", "Obtained"]
    ]
    
    kootas = ["varna", "vashya", "tara", "yoni", "graha_maitri", "gana", "bhakoot", "nadi"]
    descriptions = {
        "varna": "Work & Ego Compatibility",
        "vashya": "Attraction & Control",
        "tara": "Destiny & Health",
        "yoni": "Intimacy & Biology",
        "graha_maitri": "Mental Compatibility",
        "gana": "Temperament",
        "bhakoot": "Love & Family Growth",
        "nadi": "Health & Genetics"
    }
    
    for k in kootas:
        k_data = ashtakoota_score.get(k, {})
        guna_data.append([
            k.capitalize(),
            descriptions.get(k, ""),
            str(k_data.get("max", 0)),
            str(k_data.get("score", 0))
        ])
    
    # Total
    total_data = ashtakoota_score.get("total_score", {})
    guna_data.append([
        "Total Score",
        "",
        str(total_data.get("max", 36)),
        str(total_data.get("score", 0))
    ])
    
    t2 = Table(guna_data, colWidths=[1.5*inch, 2.5*inch, 1*inch, 1.5*inch])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.beige),
        ('BACKGROUND', (0,-1), (-1,-1), colors.lightgreen),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,-1), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    story.append(t2)
    story.append(Spacer(1, 0.4*inch))
    
    # Conclusion
    story.append(Paragraph("<b>Conclusion & Result</b>", styles['Heading2']))
    story.append(Spacer(1, 0.1*inch))
    story.append(Paragraph(f"{result_message}", styles['Normal']))
    
    doc.build(story)
