
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
import os
from datetime import datetime

def create_kundli_pdf(filename, dob, tob, lat, lon, kundli_data, avastha_data, panchang_data):
    doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title = Paragraph(f"<b><font size=16>Hindu Vedic Kundli Report</font></b><br/><font size=10>Generated by My Hindu API V4</font>", styles['Normal'])
    story.append(title)
    story.append(Spacer(1, 0.3*inch))
    
    # Birth Details
    details = [
        ["Birth Date", dob],
        ["Birth Time", tob],
        ["Latitude", str(lat)],
        ["Longitude", str(lon)],
        ["Ayanamsa", "Lahiri"],
        ["Generated On", datetime.now().strftime("%Y-%m-%d %H:%M")]
    ]
    t = Table(details, colWidths=[2*inch, 3*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2*inch))
    
    # Janma Details
    story.append(Paragraph("<b>Janma Details</b>", styles['Heading2']))
    janma = [
        ["Janma Rashi", kundli_data.get("janma_rashi","")],
        ["Janma Nakshatra", kundli_data.get("janma_nakshatra","")],
        ["Ascendant", f"{kundli_data.get('ascendant',{}).get('rashi','')} ({kundli_data.get('ascendant',{}).get('degree','')}°)"]
    ]
    t2 = Table(janma, colWidths=[2*inch, 3*inch])
    t2.setStyle(TableStyle([('BACKGROUND', (0,0), (0,-1), colors.beige),('GRID', (0,0), (-1,-1), 1, colors.black),('FONTSIZE', (0,0), (-1,-1), 10)]))
    story.append(t2)
    story.append(Spacer(1, 0.2*inch))
    
    # Planets Table
    story.append(Paragraph("<b>Graha Sthiti - Planet Positions</b>", styles['Heading2']))
    planet_rows = [["Graha","Rashi","Degree","Nakshatra","Avastha (Deeptadi)","Shayanadi"]]
    for p in kundli_data.get("planets",[]):
        name = p.get("name","")
        av = avastha_data.get(name, {}) if avastha_data else {}
        deeptadi = av.get("deeptadi",{}).get("en","") if av else ""
        shayanadi = av.get("shayanadi",{}).get("en","") if av else ""
        planet_rows.append([
            name,
            p.get("rashi",""),
            str(p.get("degree","")),
            p.get("nakshatra",""),
            deeptadi,
            shayanadi
        ])
    t3 = Table(planet_rows, colWidths=[0.8*inch, 1*inch, 0.7*inch, 1*inch, 0.8*inch, 0.8*inch])
    t3.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.black),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.lightgrey])
    ]))
    story.append(t3)
    story.append(Spacer(1, 0.3*inch))
    
    # Panchang if available
    if panchang_data:
        story.append(Paragraph("<b>Panchang on Birth Day</b>", styles['Heading2']))
        pan_rows = [
            ["Tithi", f"{panchang_data.get('tithi',{}).get('name','')} ({panchang_data.get('tithi',{}).get('number','')})"],
            ["Nakshatra", panchang_data.get('nakshatra',{}).get('name','')],
            ["Yoga", panchang_data.get('yoga',{}).get('name','')],
            ["Karana", panchang_data.get('karana',{}).get('name','')],
            ["Vara", panchang_data.get('vara','')]
        ]
        t4 = Table(pan_rows, colWidths=[2*inch, 3*inch])
        t4.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, colors.black),('FONTSIZE', (0,0), (-1,-1), 9)]))
        story.append(t4)
    
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("<font size=8>This is computer generated report based on Lahiri Ayanamsa and Swiss Ephemeris. For precise muhurta consult learned Pandit. Generated by My Hindu API V4.</font>", styles['Normal']))
    
    doc.build(story)
    return filename
